### ISSUE TITLE
Code not matching paper

### ISSUE THREAD

**Issue by rohansaphal97** [jaesik817/Interaction-networks_tensorflow#6]
Hi,

There are a things that are not matching with whats written on the paper. Hope you could help me understand?

1.) Instead of concatenation, you have subtracted the two vectors for the first step in function def m()--->line 30. You have provided a correction on line 31 but its commented. Any reason?

2.)In line 37, the vector B should be reshaped to 2*Ds+Dr as given in the paper. Any reason for the modification?

3.)Why the modification in line 59??

4.)why the modification in line 66?. Why is there a 2 added while reshaping. In the paper, its Ds+Dx+De

5.)While normalizing, why have you indexed at the number of body index. i.e train_data[: , 0 , :]--->line 166
Same happens with other values till line 177. Isnt the normalization supposed to happen on the third index? i.e train_data[: , : , 0] ??? 

6.) Why is the value of X matrix all zeros. isn't there gravitational forces acting on the bodies??

Hope to hear from you soon.

Thanks in advance

**Comment by jsikyoon** [comment]
Hi,

First of all, sorry for late response.

I will reply your questions as soon as possible after re-checking my code on my side, because I forgot somethings on there, which was implemented in last year.

I remember I changed somethings (maybe m() concat. to diff.) on during of validating my code with my own data generator.

However, I remember I was not changing not too many things. anyway I will catch-up your ones, and reply answer for those questions.

Thank you for your attention on my repo.

Best Regards, Jaesik Yoon.

**Comment by jsikyoon** [comment]
1.) Instead of concatenation, you have subtracted the two vectors for the first step in function def m()--->line 30. You have provided a correction on line 31 but its commented. Any reason?

-> I remember diff. showed better performance than concat. Actually for gravity experiment, core information is how far from each other, thus I tried to use diff.

2.)In line 37, the vector B should be reshaped to 2*Ds+Dr as given in the paper. Any reason for the modification?

-> not using concat but diff, thus 2*Ds -> Ds

3.)Why the modification in line 59??

-> that is also for getting better performance, on prediction or inference state, mass or location don't affect to performance, thus cuted those dimension on there.

4.)why the modification in line 66?. Why is there a 2 added while reshaping. In the paper, its Ds+Dx+De

-> just using x and y vel. not total Ds, thus Ds -> 2

5.)While normalizing, why have you indexed at the number of body index. i.e train_data[: , 0 , :]--->line 166
Same happens with other values till line 177. Isnt the normalization supposed to happen on the third index? i.e train_data[: , : , 0] ???

-> which is not normalization with body index, middle index is one of Ds. 
in 166, train_data[:,0,:] means mass values normalization on total objs.

6.) Why is the value of X matrix all zeros. isn't there gravitational forces acting on the bodies??

-> yes just naiive n-body experiment not with external force.
